# Generated by Django 2.1.7 on 2019-03-21 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('turf_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('units', models.CharField(max_length=20, null=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('done_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('width', models.DecimalField(decimal_places=3, max_digits=10)),
                ('length', models.DecimalField(decimal_places=3, max_digits=10)),
                ('units', models.CharField(max_length=20, null=True)),
                ('units_dimension', models.CharField(max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='fertiliser',
            old_name='potassium',
            new_name='K',
        ),
        migrations.RenameField(
            model_name='fertiliser',
            old_name='magnesium',
            new_name='Mg',
        ),
        migrations.RenameField(
            model_name='fertiliser',
            old_name='nitrogen',
            new_name='N',
        ),
        migrations.RenameField(
            model_name='fertiliser',
            old_name='phosphorus',
            new_name='P',
        ),
        migrations.AddField(
            model_name='distributor',
            name='user',
            field=models.ManyToManyField(related_name='distributors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='user',
            field=models.ManyToManyField(related_name='manufacturers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='units',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='turf_app.Field'),
        ),
        migrations.AddField(
            model_name='application',
            name='products',
            field=models.ManyToManyField(related_name='applications', to='turf_app.Product'),
        ),
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
    ]
