# Generated by Django 2.1.7 on 2019-03-22 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('turf_app', '0002_auto_20190321_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributorUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FertiliserUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('stock', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('price', models.DecimalField(decimal_places=3, default=1.0, max_digits=10)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fertilisers', to='turf_app.DistributorUser')),
            ],
        ),
        migrations.RemoveField(
            model_name='application',
            name='products',
        ),
        migrations.RemoveField(
            model_name='distributor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='product',
            name='distributor',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='distributor',
            name='manufacturers',
            field=models.ManyToManyField(related_name='distributors', to='turf_app.Manufacturer'),
        ),
        migrations.AddField(
            model_name='fertiliser',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='fertiliseruser',
            name='fertiliser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_by', to='turf_app.Fertiliser'),
        ),
        migrations.AddField(
            model_name='fertiliseruser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fertilisers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='distributoruser',
            name='distributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='turf_app.Distributor'),
        ),
        migrations.AddField(
            model_name='distributoruser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributors', to=settings.AUTH_USER_MODEL),
        ),
    ]
