# Generated by Django 2.1.7 on 2019-03-22 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turf_app', '0003_auto_20190322_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='FertiliserInUse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fertilisers', to='turf_app.Application')),
                ('fertiliser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='turf_app.FertiliserUser')),
            ],
        ),
    ]
