# Generated by Django 2.1.7 on 2019-03-22 15:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('turf_app', '0005_auto_20190322_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='done_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='scheduled_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 3, 22, 15, 41, 25, 133743, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='application',
            name='units',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='units',
            field=models.CharField(default='m', max_length=20),
        ),
        migrations.AlterField(
            model_name='field',
            name='units_dimension',
            field=models.CharField(default='m2', max_length=20),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(default='Fertilizer', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='units',
            field=models.CharField(default='l', max_length=20),
        ),
    ]
