# Generated by Django 2.1.7 on 2019-03-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf_app', '0007_auto_20190322_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fertiliserinuse',
            name='application',
        ),
        migrations.AddField(
            model_name='application',
            name='products',
            field=models.ManyToManyField(related_name='applications', to='turf_app.FertiliserInUse'),
        ),
    ]
