# Generated by Django 2.1.7 on 2019-03-26 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turf_app', '0008_auto_20190322_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fertiliseruser',
            name='distributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fertilisers', to='turf_app.DistributorUser'),
        ),
        migrations.AlterField(
            model_name='fertiliseruser',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fertiliseruser',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='fertilisers', to=settings.AUTH_USER_MODEL),
        ),
    ]
