# Generated by Django 2.1.7 on 2019-03-26 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turf_app', '0009_auto_20190326_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fertiliseruser',
            name='fertiliser',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='used_by', to='turf_app.Fertiliser'),
        ),
        migrations.AlterField(
            model_name='product',
            name='units',
            field=models.CharField(blank=True, default='l', max_length=20),
        ),
    ]
