# Generated by Django 2.1.7 on 2019-03-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf_app', '0011_auto_20190329_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='fertiliser',
            name='type',
            field=models.CharField(default='Liquid', max_length=50),
        ),
    ]
