# Generated by Django 2.1.7 on 2019-03-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf_app', '0013_remove_fertiliseruser_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='package',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity_per_package',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=10, null=True),
        ),
    ]
