# Generated by Django 2.1.7 on 2019-03-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf_app', '0014_auto_20190329_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='units',
            field=models.CharField(default='L', max_length=20),
        ),
    ]
