# Generated by Django 2.1.7 on 2019-04-24 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turf_app', '0015_auto_20190329_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='products',
        ),
        migrations.AddField(
            model_name='fertiliserinuse',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_used', to='turf_app.Application'),
        ),
        migrations.AlterField(
            model_name='fertiliserinuse',
            name='fertiliser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='turf_app.FertiliserUser'),
        ),
    ]
